[theme]
name = "catppuccin-mocha-blue"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#f9e2af"
AlertError = "#f38ba8"
Annotation = "#89b4fa"
Base = "#cdd6f4"
Guidance = "#9399b2"
Important = "#89b4fa"
Title = "#89b4fa"
Border = "#89b4fa"
Selection = "#313244"
